@extends('layouts.app')

@section('title', 'Login')

@section('content')
<div class="container" style="max-width: 400px; margin-top: 2rem;">
    <div class="text-center mb-2">
        <!--<div style="font-size: 3rem; margin-bottom: 1rem;">📖</div>-->
        <h1 style="font-size: 1.75rem; font-weight: 700; margin-bottom: 0.5rem;">Welcome Back</h1>
        <p class="text-secondary">Sign in to continue your learning</p>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
    @endif

    <div class="card">
        <div id="response-message" style="display:none;" class="alert"></div>
        <form method="POST" id="form" action="{{ route('login') }}">
           @csrf

            <div class="form-group">
                <label class="form-label">Email</label>
                <input type="email" name="email" class="form-input" value="{{ old('email') }}" required autofocus>
            </div>

            <div class="form-group">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-input" required>
            </div>

            <!--<div class="form-group" style="display: flex; align-items: center; gap: 0.5rem;">-->
            <!--    <input type="checkbox" name="remember" id="remember">-->
            <!--    <label for="remember" style="margin: 0; font-weight: normal;">Remember me</label>-->
            <!--</div>-->

            <button type="submit" class="btn btn-primary">Login</button>

            <div class="text-center mt-2">
                <a href="{{ route('password.request') }}" style="color: var(--primary); text-decoration: none;">Forgot Password?</a>
            </div>
        </form>
    </div>

    <div class="text-center mt-2">
        <p class="text-secondary">Don't have an account? <a href="{{ route('register') }}" style="color: var(--primary); text-decoration: none; font-weight: 600;">Sign Up</a></p>
    </div>
</div>

<script>
    document.querySelector('form').addEventListener('submit', function(e) {
    e.preventDefault(); // Prevent page reload

    const form = e.target;
    const formData = new FormData(form);
    
    // Convert FormData to a plain object for JSON submission
    const data = Object.fromEntries(formData.entries());

    fetch(form.action, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            // Grabs the token generated by @csrf in your form
            'X-CSRF-TOKEN': data._token 
        },
        body: JSON.stringify(data)
    })
    .then(async response => {
        const result = await response.json();
        
        if (response.ok) {
            // Login Success
            window.location.href = '/dashboard'; 
        } else {
            // Login Failed (e.g., validation errors)
            alert(result.message || 'Login failed. Please check your credentials.');
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert('Something went wrong. Please try again.');
    });
});
</script>
@endsection
